name: Building \e\ os using Docker

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
             git clone https://github.com/SA-17/rm_pkg p && cd p && bash setup.sh && cd $out
             sudo bash docker_installer.sh
            
            
       - name: Sync recovery source and device tree
         run: |
              mkdir work
              cd work
              sudo docker pull registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:community
               sudo mkdir -p \
              /work/src \
              /work/zips \
              /work/logs \
              /work/ccache \ 
              git clone https://github.com/LineageOS/android_packages_apps_SamsungServiceMode.git -b cm-14.1 --depth=1 --single-branch src/packages/apps/SamsungServiceMode
              git clone https://github.com/pstglia/android_device_samsung_sprd-common.git -b cm-14.1 --depth=1 --single-branch src/device/samsung/sprd-common
              git clone https://github.com/pstglia/android_device_samsung_scx30g-common.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/device/samsung/scx30g-common
              git clone https://github.com/pstglia/android_device_samsung_scx35-common.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/device/samsung/scx35-common
              git clone https://github.com/Hasajapathirana/android_device_samsung_core33g.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/device/samsung/core33g
              git clone https://github.com/pstglia/android_hardware_sprd.git -b cm-14.1 --depth=1 --single-branch src/hardware/sprd
              git clone https://github.com/LineageOS/android_hardware_samsung.git -b cm-14.1 --depth=1 --single-branch src/hardware/samsung
              git clone https://github.com/pstglia/linux.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/kernel/samsung/core33g
              git clone https://github.com/pstglia/android_vendor_samsung_core33g.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/vendor/samsung/core33g
              git clone https://github.com/pstglia/android_vendor_samsung_scx30g-common.git -b T113NU_COM_A_MAO_NO_BOLSO --depth=1 --single-branch src/vendor/samsung/scx30g-common
              sudo docker run \
              -v "/work/src:/srv/src" \
              -v "/work/zips:/srv/zips" \
              -v "/work/logs:/srv/logs" \
              -v "/work/ccache:/srv/ccache" \
              -e "BRANCH_NAME=v1-nougat" \
              -e "DEVICE_LIST=<goyave>" \
              -e "OTA_URL=<ota-server-url>" \
              -e "REPO=https://gitlab.e.foundation/e/os/android.git" \ 
              registry.gitlab.e.foundation:5000/e/os/docker-lineage-cicd:community
              
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: system.zip
            path: /home/runner/work/zips
            retention-days: 31
